<?php
namespace Database\Seeders;

use App\Models\Book;
use Illuminate\Database\Seeder;


class BooksSeeder extends Seeder
{
    public function run()
    {
        Book::insert([
            [
                'title' => 'Книга 1',
                'slug'  => 'book-1',
                'year'  => random_int(1,9999),
                'author_id' => 1,
                'description' => 'Описание книги 1',
                'category_id' => '1',
                'cover' => '',
            ],
            [
                'title' => 'Книга 2',
                'slug'  => 'book-2',
                'year'  => random_int(1,9999),
                'author_id' => 2,
                'description' => 'Описание книги 2',
                'category_id' => '1',
                'cover' => '',
            ],
            [
                'title' => 'Книга 3',
                'slug'  => 'book-3',
                'year'  => random_int(1,9999),
                'author_id' => 3,
                'description' => 'Описание книги 3',
                'category_id' => '1',
                'cover' => '',
            ],
            [
                'title' => 'Книга 4',
                'slug'  => 'book-4',
                'year'  => random_int(1,9999),
                'author_id' => 4,
                'description' => 'Описание книги 4',
                'category_id' => '1',
                'cover' => '',
            ],
            [
                'title' => 'Книга 5',
                'slug'  => 'book-5',
                'year'  => random_int(1,9999),
                'author_id' => 5,
                'description' => 'Описание книги 5',
                'category_id' => '1',
                'cover' => '',
            ],
            [
                'title' => 'Книга 6',
                'slug'  => 'book-6',
                'year'  => random_int(1,9999),
                'author_id' => 6,
                'description' => 'Описание книги 6',
                'category_id' => '1',
                'cover' => '',
            ],
            [
                'title' => 'Книга 7',
                'slug'  => 'book-7',
                'year'  => random_int(1,9999),
                'author_id' => 7,
                'description' => 'Описание книги 7',
                'category_id' => '1',
                'cover' => '',
            ],
            [
                'title' => 'Книга 8',
                'slug'  => 'book-8',
                'year'  => random_int(1,9999),
                'author_id' => 8,
                'description' => 'Описание книги 8',
                'category_id' => '1',
                'cover' => '',
            ],
            [
                'title' => 'Книга 9',
                'slug'  => 'book-9',
                'year'  => random_int(1,9999),
                'author_id' => 9,
                'description' => 'Описание книги 9',
                'category_id' => '1',
                'cover' => '',
            ],
            [
                'title' => 'Книга 10',
                'slug'  => 'book-10',
                'year'  => random_int(1,9999),
                'author_id' => 10,
                'description' => 'Описание книги 10',
                'category_id' => '1',
                'cover' => '',
            ],
            [
                'title' => 'Книга 11',
                'slug'  => 'book-11',
                'year'  => random_int(1,9999),
                'author_id' => 11,
                'description' => 'Описание книги 11',
                'category_id' => '2',
                'cover' => '',
            ],
            [
                'title' => 'Книга 12',
                'slug'  => 'book-12',
                'year'  => random_int(1,9999),
                'author_id' => 12,
                'description' => 'Описание книги 12',
                'category_id' => '2',
                'cover' => '',
            ],
            [
                'title' => 'Книга 13',
                'slug'  => 'book-13',
                'year'  => random_int(1,9999),
                'author_id' => 13,
                'description' => 'Описание книги 13',
                'category_id' => '2',
                'cover' => '',
            ],
            [
                'title' => 'Книга 14',
                'slug'  => 'book-14',
                'year'  => random_int(1,9999),
                'author_id' => 14,
                'description' => 'Описание книги 14',
                'category_id' => '2',
                'cover' => '',
            ],
            [
                'title' => 'Книга 15',
                'slug'  => 'book-15',
                'year'  => random_int(1,9999),
                'author_id' => 15,
                'description' => 'Описание книги 15',
                'category_id' => '2',
                'cover' => '',
            ],
            [
                'title' => 'Книга 16',
                'slug'  => 'book-16',
                'year'  => random_int(1,9999),
                'author_id' => 16,
                'description' => 'Описание книги 16',
                'category_id' => '2',
                'cover' => '',
            ],
            [
                'title' => 'Книга 17',
                'slug'  => 'book-17',
                'year'  => random_int(1,9999),
                'author_id' => 17,
                'description' => 'Описание книги 17',
                'category_id' => '2',
                'cover' => '',
            ],
            [
                'title' => 'Книга 18',
                'slug'  => 'book-18',
                'year'  => random_int(1,9999),
                'author_id' => 18,
                'description' => 'Описание книги 18',
                'category_id' => '2',
                'cover' => '',
            ],
            [
                'title' => 'Книга 19',
                'slug'  => 'book-19',
                'year'  => random_int(1,9999),
                'author_id' => 19,
                'description' => 'Описание книги 19',
                'category_id' => '2',
                'cover' => '',
            ],
            [
                'title' => 'Книга 20',
                'slug'  => 'book-20',
                'year'  => random_int(1,9999),
                'author_id' => 20,
                'description' => 'Описание книги 20',
                'category_id' => '2',
                'cover' => '',
            ],
            [
                'title' => 'Книга 21',
                'slug'  => 'book-21',
                'year'  => random_int(1,9999),
                'author_id' => 21,
                'description' => 'Описание книги 21',
                'category_id' => '3',
                'cover' => '',
            ],
            [
                'title' => 'Книга 22',
                'slug'  => 'book-22',
                'year'  => random_int(1,9999),
                'author_id' => 22,
                'description' => 'Описание книги 22',
                'category_id' => '3',
                'cover' => '',
            ],
            [
                'title' => 'Книга 23',
                'slug'  => 'book-23',
                'year'  => random_int(1,9999),
                'author_id' => 23,
                'description' => 'Описание книги 23',
                'category_id' => '3',
                'cover' => '',
            ],
            [
                'title' => 'Книга 24',
                'slug'  => 'book-24',
                'year'  => random_int(1,9999),
                'author_id' => 24,
                'description' => 'Описание книги 24',
                'category_id' => '3',
                'cover' => '',
            ],
            [
                'title' => 'Книга 25',
                'slug'  => 'book-25',
                'year'  => random_int(1,9999),
                'author_id' => 25,
                'description' => 'Описание книги 25',
                'category_id' => '3',
                'cover' => '',
            ],
            [
                'title' => 'Книга 26',
                'slug'  => 'book-26',
                'year'  => random_int(1,9999),
                'author_id' => 26,
                'description' => 'Описание книги 26',
                'category_id' => '3',
                'cover' => '',
            ],
            [
                'title' => 'Книга 27',
                'slug'  => 'book-27',
                'year'  => random_int(1,9999),
                'author_id' => 27,
                'description' => 'Описание книги 27',
                'category_id' => '3',
                'cover' => '',
            ],
            [
                'title' => 'Книга 28',
                'slug'  => 'book-28',
                'year'  => random_int(1,9999),
                'author_id' => 28,
                'description' => 'Описание книги 28',
                'category_id' => '3',
                'cover' => '',
            ],
            [
                'title' => 'Книга 29',
                'slug'  => 'book-29',
                'year'  => random_int(1,9999),
                'author_id' => 29,
                'description' => 'Описание книги 29',
                'category_id' => '3',
                'cover' => '',
            ],
            [
                'title' => 'Книга 30',
                'slug'  => 'book-30',
                'year'  => random_int(1,9999),
                'author_id' => 30,
                'description' => 'Описание книги 30',
                'category_id' => '3',
                'cover' => '',
            ],
            [
                'title' => 'Книга 31',
                'slug'  => 'book-31',
                'year'  => random_int(1,9999),
                'author_id' => 31,
                'description' => 'Описание книги 31',
                'category_id' => '4',
                'cover' => '',
            ],
            [
                'title' => 'Книга 32',
                'slug'  => 'book-32',
                'year'  => random_int(1,9999),
                'author_id' => 32,
                'description' => 'Описание книги 32',
                'category_id' => '4',
                'cover' => '',
            ],
            [
                'title' => 'Книга 33',
                'slug'  => 'book-33',
                'year'  => random_int(1,9999),
                'author_id' => 33,
                'description' => 'Описание книги 33',
                'category_id' => '4',
                'cover' => '',
            ],
            [
                'title' => 'Книга 34',
                'slug'  => 'book-34',
                'year'  => random_int(1,9999),
                'author_id' => 34,
                'description' => 'Описание книги 34',
                'category_id' => '4',
                'cover' => '',
            ],
            [
                'title' => 'Книга 35',
                'slug'  => 'book-35',
                'year'  => random_int(1,9999),
                'author_id' => 35,
                'description' => 'Описание книги 35',
                'category_id' => '4',
                'cover' => '',
            ],
            [
                'title' => 'Книга 36',
                'slug'  => 'book-36',
                'year'  => random_int(1,9999),
                'author_id' => 36,
                'description' => 'Описание книги 36',
                'category_id' => '4',
                'cover' => '',
            ],
            [
                'title' => 'Книга 37',
                'slug'  => 'book-37',
                'year'  => random_int(1,9999),
                'author_id' => 37,
                'description' => 'Описание книги 37',
                'category_id' => '4',
                'cover' => '',
            ],
            [
                'title' => 'Книга 38',
                'slug'  => 'book-38',
                'year'  => random_int(1,9999),
                'author_id' => 38,
                'description' => 'Описание книги 38',
                'category_id' => '4',
                'cover' => '',
            ],
            [
                'title' => 'Книга 39',
                'slug'  => 'book-39',
                'year'  => random_int(1,9999),
                'author_id' => 39,
                'description' => 'Описание книги 39',
                'category_id' => '4',
                'cover' => '',
            ],
            [
                'title' => 'Книга 40',
                'slug'  => 'book-40',
                'year'  => random_int(1,9999),
                'author_id' => 40,
                'description' => 'Описание книги 40',
                'category_id' => '4',
                'cover' => '',
            ],
            [
                'title' => 'Книга 41',
                'slug'  => 'book-41',
                'year'  => random_int(1,9999),
                'author_id' => 41,
                'description' => 'Описание книги 41',
                'category_id' => '5',
                'cover' => '',
            ],
            [
                'title' => 'Книга 42',
                'slug'  => 'book-42',
                'year'  => random_int(1,9999),
                'author_id' => 42,
                'description' => 'Описание книги 42',
                'category_id' => '5',
                'cover' => '',
            ],
            [
                'title' => 'Книга 43',
                'slug'  => 'book-43',
                'year'  => random_int(1,9999),
                'author_id' => 43,
                'description' => 'Описание книги 43',
                'category_id' => '5',
                'cover' => '',
            ],
            [
                'title' => 'Книга 44',
                'slug'  => 'book-44',
                'year'  => random_int(1,9999),
                'author_id' => 44,
                'description' => 'Описание книги 44',
                'category_id' => '5',
                'cover' => '',
            ],
            [
                'title' => 'Книга 45',
                'slug'  => 'book-45',
                'year'  => random_int(1,9999),
                'author_id' => 45,
                'description' => 'Описание книги 45',
                'category_id' => '5',
                'cover' => '',
            ],
            [
                'title' => 'Книга 46',
                'slug'  => 'book-46',
                'year'  => random_int(1,9999),
                'author_id' => 46,
                'description' => 'Описание книги 46',
                'category_id' => '5',
                'cover' => '',
            ],
            [
                'title' => 'Книга 47',
                'slug'  => 'book-47',
                'year'  => random_int(1,9999),
                'author_id' => 47,
                'description' => 'Описание книги 47',
                'category_id' => '5',
                'cover' => '',
            ],
            [
                'title' => 'Книга 48',
                'slug'  => 'book-48',
                'year'  => random_int(1,9999),
                'author_id' => 48,
                'description' => 'Описание книги 48',
                'category_id' => '5',
                'cover' => '',
            ],
            [
                'title' => 'Книга 49',
                'slug'  => 'book-49',
                'year'  => random_int(1,9999),
                'author_id' => 49,
                'description' => 'Описание книги 49',
                'category_id' => '5',
                'cover' => '',
            ],
            [
                'title' => 'Книга 50',
                'slug'  => 'book-50',
                'year'  => random_int(1,9999),
                'author_id' => 50,
                'description' => 'Описание книги 50',
                'category_id' => '5',
                'cover' => '',
            ],
        ]);
    }
}

